---
name: Super-Linter

on: 
  push:
  fork:
  workflow_dispatch:

jobs:
  super-linter:
    name: Super Linter Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Super-Linter
        uses: github/super-linter@v4.9.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
